package com.example.studkotlindroid.numbersList

object PhoneNumberData {
    val randomNumbers = listOf("89998629804", "89153524382", "89162930684", "89998003245", "*100#", "8BBB", "895432", "123423515124124")
    private fun getList() = listOf(
        PhoneNumber("Svistov", randomNumbers[0]),
        PhoneNumber("Anton", randomNumbers[1]),
        PhoneNumber("Money", randomNumbers[4]),
        PhoneNumber("BBB", randomNumbers[5]),
        PhoneNumber("Mum", randomNumbers[2]),
        PhoneNumber("Brother", randomNumbers[3]),
        PhoneNumber("AAA", randomNumbers[6]),
        PhoneNumber("Svistov", randomNumbers[0]),
        PhoneNumber("Anton", randomNumbers[1]),
        PhoneNumber("Money", randomNumbers[4]),
        PhoneNumber("BBB", randomNumbers[5]),
        PhoneNumber("Mum", randomNumbers[2]),
        PhoneNumber("Brother", randomNumbers[3]),
        PhoneNumber("AAA", randomNumbers[6]),
        PhoneNumber("Svistov", randomNumbers[0]),
        PhoneNumber("Anton", randomNumbers[1]),
        PhoneNumber("Money", randomNumbers[4]),
        PhoneNumber("BBB", randomNumbers[5]),
        PhoneNumber("Mum", randomNumbers[2]),
        PhoneNumber("Brother", randomNumbers[3]),
        PhoneNumber("AAA", randomNumbers[6]),
        PhoneNumber("Svistov", randomNumbers[0]),
        PhoneNumber("Anton", randomNumbers[1]),
        PhoneNumber("Money", randomNumbers[4]),
        PhoneNumber("BBB", randomNumbers[5]),
        PhoneNumber("Mum", randomNumbers[2]),
        PhoneNumber("Brother", randomNumbers[3]),
        PhoneNumber("AAA", randomNumbers[6]),
        PhoneNumber("Svistov", randomNumbers[0]),
        PhoneNumber("Anton", randomNumbers[1]),
        PhoneNumber("Money", randomNumbers[4]),
        PhoneNumber("BBB", randomNumbers[5]),
        PhoneNumber("Mum", randomNumbers[2]),
        PhoneNumber("Brother", randomNumbers[3]),
        PhoneNumber("AAA", randomNumbers[6]),
        PhoneNumber("Svistov", randomNumbers[0]),
        PhoneNumber("Anton", randomNumbers[1]),
        PhoneNumber("Money", randomNumbers[4]),
        PhoneNumber("BBB", randomNumbers[5]),
        PhoneNumber("Mum", randomNumbers[2]),
        PhoneNumber("Brother", randomNumbers[3]),
        PhoneNumber("AAA", randomNumbers[6]),
        PhoneNumber("Zzzz", randomNumbers[7]),
        PhoneNumber("SSSer", randomNumbers[7]),
        PhoneNumber("Zzzz", randomNumbers[7]),
        PhoneNumber("USSr", randomNumbers[7]),
        PhoneNumber("Zzzz", randomNumbers[7]),
        PhoneNumber("GGG", randomNumbers[7]),
        PhoneNumber("GGG", randomNumbers[7]),
        PhoneNumber("Zzzz", randomNumbers[7]),
        PhoneNumber("Zzzz", randomNumbers[7]),
    )
    fun getGrouped() : Map<Char,List<PhoneNumber>> {
        return getList().sortedBy { it.Name }.groupBy { it.firstSymbol }
    }
}